# baseURL: https://kaelo.dev
baseURL: https://kaelo.netlify.app/

languageCode: en-us
title: Kaelo
theme: hugo-theme-console

params:
  titleCutting: true
  animateStyle: "animated zoomIn fast"
  navlinks:
    - name: "posts/"
      url: "posts/"
    - name: "tshimo/"
      url: "tshimo/"
